# Arrays Slicing & indexing

It is very important to first understand how basic indexing and slicing works in Python.

In [30]:
s = "Python"

Now as we access(Or, Should I say slice?) please refer to the above index table. That way you will understand things easily

In [31]:
s[1] # Look at the first row of the index table. This will return 'y'

'y'

In [32]:
s[-1] # Look at the second row. This will return 'n'

'n'

# Python Slicing mechanism
**Syntax  : L[start:end:stride]**

Ever since Python 1.4, the slicing syntax has supported an optional third `step` or `stride` argument. For example, these are all legal Python syntax: L[1:10:2], L[:-1:1], L[::-1]. This was added to Python at the request of the developers of Numerical Python, which uses the third argument extensively.

Let us have a look at a few examples :

In [45]:
s[0:2]  # characters from position 0 (included) to 2 (excluded)

'Py'

In [34]:
L = range(10)
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
L[0:10] #start = 0, end = 10(excluded), stride = 1 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
L[::] # No slicing indices provided? Return everything!

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Now, comes the fun part!

In [35]:
L[::2] #you can now easily extract the elements of a list that have even indexes.

[0, 2, 4, 6, 8]

In [38]:
L[::-2] #Take strides of 2 but from the back

[9, 7, 5, 3, 1]

# NUMPY ARRAY Slicing
Arrays in numpy are similar to Python Lists, except that they should always have elements of the same type i.e. `float` or `int`. Now, we will learn about array slicing and indexing. 

**CAUTION** : This will need thorough understanding of basic list slicing in Python(explained above). Make sure you have understood that well

In [1]:
import numpy as np
A = np.array([1, 2, 3, 5, 6, 7], float)

In [2]:
A

array([ 1.,  2.,  3.,  5.,  6.,  7.])

In [3]:
type(A)

numpy.ndarray

In [5]:
A[:2]

array([ 1.,  2.])

In [6]:
A[3]

5.0

Arrays can also be multidimensional. 

In [7]:
b = np.array([[1, 2, 3,], [4, 5, 6]], float)

In [8]:
b

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [23]:
b[:2] # Get me everything from 0th row until 2nd Row(1st Axis). This is same as b[:2,]

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [10]:
b[1:2] # Dealing in the first Axis i.e. Rows. Get me everything that starts from 2nd row until the 2nd Row 

array([[ 4.,  5.,  6.]])

Unlike lists, different axes are accessed using commas inside
bracket notation.

In [12]:
b[1:,] # First Axis - Get me the first row. 2nd Axis: get me everything in the column

array([[ 4.,  5.,  6.]])

In [13]:
b[1:] # Same as above.

array([[ 4.,  5.,  6.]])

In [16]:
b[:,2] # Get me everything of the first Axis, but from 3rd Column(2nd Axis)

array([ 3.,  6.])

In [17]:
b[-1:] # Get me the last row

array([[ 4.,  5.,  6.]])

In [25]:
b[:-1] 

array([[ 1.,  2.,  3.]])

In [19]:
b[-1:,]

array([[ 4.,  5.,  6.]])

In [20]:
b[-1:, -2:]

array([[ 5.,  6.]])

In [21]:
b[-1:,]

array([[ 4.,  5.,  6.]])

In [22]:
b[-1:, ::-2] # Everything in the last row(-1) and pick elements from the last column at strides of 2

array([[ 6.,  4.]])